### ISSUE TITLE
Training always prompts errors

### ISSUE THREAD

**Issue by zhongjiansheng** [Reagan1311/DABNet#33] opened 2020-01-07 07:05 UTC
File "/home/stu/user/jszhong/Research/DABNet/dataset/cityscapes.py", line 64, in __getitem__
    label = cv2.resize(label, None, fx=f_scale, fy=f_scale, interpolation=cv2.INTER_NEAREST)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by Reagan1311** [comment] 2020-01-08 05:23
Duplicate of #28 , please refer to this issus

**Closed as completed** 2020-01-08 05:24 UTC
